### ISSUE TITLE
No matching version found for switchery@0.8.2

### ISSUE THREAD

**Issue by maaliHasan** [bettimms/ui-switchery#1]
I'm trying to download **ui-switchery** using $ npm install ui-switchery  but I got the following error  ::

"npm ERR! code ETARGET
npm ERR! notarget No matching version found for switchery@0.8.2
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ui-switchery'
npm ERR! notarget ".

So , I tried to update the switchery [version](https://www.npmjs.com/package/switchery)  but I couldn't find  the required version which ui-switchery need it ? 

PS : I don't want to use the bower to install the packages.

**Comment by bettimms** [comment]
As I'm seeing you've problems with switchery library itself. So go grab right version of switchery because seems 0.8.2 doesn't exist ( I'm seeing that 0.0.2 is the current version of it) then try to install ui-switchery (version 1.0.0-beta.1).

**Comment by maaliHasan** [comment]
@bettimms , I did download the current version of switchery (0.0.2) . But the problem is when I try to download the ui-switchery (version 1.0.0-beta.1) which required the **switchrey  version ~0.8.1**[ as an dependency  ](https://github.com/bettimms/ui-switchery/blob/master/package.json) !

**Comment by bettimms** [comment]
It seems broken, I'll update it later today!

**Comment by bettimms** [comment]
I updated the version and removed that dependency! Have a look now!

**Comment by maaliHasan** [comment]
Thanks !  it works perfectly now  👍
